#!/usr/bin/env bash
#
# KumaCode Installer
# curl -fsSL https://raw.githubusercontent.com/kumavolt/kumacode/main/install.sh | bash
#
# What it does:
#   1. Installs Bun if not already present
#   2. Clones (or updates) the kumacode repo to ~/.kumacode/app
#   3. Installs dependencies with bun
#   4. Creates a 'kumacode' launcher script in ~/.local/bin (or custom PREFIX)
#   5. Ensures ~/.local/bin is in PATH
#
set -euo pipefail

# --- Configuration ---
REPO_URL="${KUMACODE_REPO:-https://github.com/kumavolt/kumacode.git}"
BRANCH="${KUMACODE_BRANCH:-main}"
INSTALL_DIR="${KUMACODE_HOME:-$HOME/.kumacode/app}"
BIN_DIR="${KUMACODE_BIN_DIR:-$HOME/.local/bin}"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

info()  { printf "${CYAN}${BOLD}[kumacode]${RESET} %s\n" "$*"; }
ok()    { printf "${GREEN}${BOLD}[kumacode]${RESET} %s\n" "$*"; }
warn()  { printf "${YELLOW}${BOLD}[kumacode]${RESET} %s\n" "$*"; }
err()   { printf "${RED}${BOLD}[kumacode]${RESET} %s\n" "$*" >&2; }

# --- Detect OS ---
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
  Darwin|Linux) ;;
  *) err "Unsupported OS: $OS"; exit 1 ;;
esac

# --- Find or install Bun ---
find_bun() {
  if command -v bun &>/dev/null; then
    echo "bun"
    return
  fi
  if [ -x "$HOME/.bun/bin/bun" ]; then
    echo "$HOME/.bun/bin/bun"
    return
  fi
  return 1
}

install_bun() {
  info "Bun not found. Installing Bun..."
  curl -fsSL https://bun.sh/install | bash
  if [ -x "$HOME/.bun/bin/bun" ]; then
    ok "Bun installed at ~/.bun/bin/bun"
  else
    err "Bun installation failed"
    exit 1
  fi
}

BUN=""
if BUN=$(find_bun); then
  ok "Found Bun at: $BUN"
else
  install_bun
  BUN="$HOME/.bun/bin/bun"
fi

BUN_VERSION=$("$BUN" --version 2>/dev/null || echo "unknown")
info "Bun version: $BUN_VERSION"

# --- Find or install Git ---
if ! command -v git &>/dev/null; then
  err "Git is required but not found. Please install git first."
  exit 1
fi

# --- Clone or update the repo ---
if [ -d "$INSTALL_DIR/.git" ]; then
  info "Updating existing installation at $INSTALL_DIR..."
  cd "$INSTALL_DIR"
  git fetch origin "$BRANCH" --quiet
  git checkout "$BRANCH" --quiet 2>/dev/null || git checkout -b "$BRANCH" "origin/$BRANCH" --quiet
  git reset --hard "origin/$BRANCH" --quiet
  ok "Updated to latest $BRANCH"
else
  info "Cloning KumaCode to $INSTALL_DIR..."
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR" --quiet
  ok "Cloned to $INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# --- Install dependencies ---
info "Installing dependencies..."
"$BUN" install --frozen-lockfile 2>/dev/null || "$BUN" install
ok "Dependencies installed"

# --- Create launcher script ---
mkdir -p "$BIN_DIR"

LAUNCHER="$BIN_DIR/kumacode"
cat > "$LAUNCHER" << LAUNCHER_EOF
#!/usr/bin/env bash
# KumaCode launcher — generated by install.sh
set -euo pipefail

# Find bun
BUN=""
if command -v bun &>/dev/null; then
  BUN="bun"
elif [ -x "\$HOME/.bun/bin/bun" ]; then
  BUN="\$HOME/.bun/bin/bun"
else
  echo "Error: Bun runtime not found. Re-run the KumaCode installer." >&2
  exit 1
fi

exec "\$BUN" run "$INSTALL_DIR/packages/cli/src/index.ts" "\$@"
LAUNCHER_EOF

chmod +x "$LAUNCHER"
ok "Launcher created at $LAUNCHER"

# --- Ensure BIN_DIR is in PATH ---
add_to_path_if_needed() {
  local shell_rc=""
  local current_shell
  current_shell="$(basename "${SHELL:-/bin/bash}")"

  case "$current_shell" in
    zsh)  shell_rc="$HOME/.zshrc" ;;
    bash)
      if [ -f "$HOME/.bash_profile" ]; then
        shell_rc="$HOME/.bash_profile"
      else
        shell_rc="$HOME/.bashrc"
      fi
      ;;
    fish) shell_rc="$HOME/.config/fish/config.fish" ;;
    *)    shell_rc="$HOME/.profile" ;;
  esac

  # Check if BIN_DIR is already in PATH
  if echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    return 0
  fi

  if [ -n "$shell_rc" ] && [ -f "$shell_rc" ]; then
    if grep -q "$BIN_DIR" "$shell_rc" 2>/dev/null; then
      return 0
    fi
  fi

  info "Adding $BIN_DIR to PATH in $shell_rc..."
  if [ "$current_shell" = "fish" ]; then
    echo "fish_add_path $BIN_DIR" >> "$shell_rc"
  else
    echo "" >> "$shell_rc"
    echo "# KumaCode" >> "$shell_rc"
    echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$shell_rc"
  fi
  warn "PATH updated. Restart your terminal or run: source $shell_rc"
}

add_to_path_if_needed

# --- Done ---
echo ""
ok "KumaCode installed successfully!"
echo ""
info "Get started:"
echo "  kumacode connect    # Set up a model provider (GitHub Copilot, OpenAI, etc.)"
echo "  kumacode            # Start coding with KumaCode"
echo "  kumacode --help     # See all options"
echo ""
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
  warn "Remember to restart your terminal or run: export PATH=\"$BIN_DIR:\$PATH\""
fi
